[package]
name = "voxurf-extension"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore = "0.8"
sycamore-router = "0.8.0"
wasm-bindgen = "0.2"
voxurf = { version = "0.1.0", path = "../voxurf" }


[lib]
crate-type = [ "cdylib", "rlib" ]
