version="0.3.2"

[scripts]
# Dependencies: `wasm-pack`
build.cmd = [
    "cd packages/voxurf-extension",
    "tailwindcss -i index.css -o tailwind.css",
    "wasm-pack build --dev --target web"
]
watch = "cargo watch -s \"bonnie build\""
build.subcommands.--prod = [
    "cd packages/voxurf-extension",
    "NODE_ENV=production tailwindcss -i index.css -o tailwind.css",
    "wasm-pack build --target web"
]
server = [
    "cd packages/voxurf-server",
    "cargo run"
]
prepare = [
    "cargo install wasm-pack cargo-watch",
    "cargo build"
]

do = "concurrently \"bonnie watch\" \"bonnie server\""
